version: '3.9'
services:
    web-nginx:
        image: nginx:latest
        container_name: web-nginx
        volumes:
            - "./docker-web/www:/usr/share/nginx/html"
            - "./docker-web/log:/var/log/nginx"
            - "./docker-web/nginx.conf:/etc/nginx/nginx.conf"
        ports:
            - "8095:80"

    web-php:
        image: php:fpm-alpine
        build: ./docker-web/
        container_name: web-php
        volumes:
            - "./docker-web/www:/script:ro"
    web-pgsql:
        image: postgres
        container_name: web-pgsql
        mem_limit: 512m
        environment:
            - POSTGRES_PASSWORD=pwd
            - POSTGRES_USER=root
            - POSTGRES_DB=univers
        command: postgres -c max_connections=300 -c log_min_messages=LOG
        ports:
            - "5432:5432"
