version: '3'

services:
    web-nginx:
        image: nginx:stable-alpine
        container_name: web-nginx
        volumes:
            - "./docker-web/www:/usr/share/nginx/html"
            - "./docker-web/log:/var/log/nginx"
            - "./docker-web/nginx.conf:/etc/nginx/nginx.conf"
        ports:
            - "127.0.0.1:8095:80"

    web-php:
        image: php:fpm-alpine
        build: ./docker-web/
        container_name: web-php
        volumes:
            - "./docker-web/www:/script:ro"
            
    web-pgsql:
        image: postgres:alpine
        container_name: web-pgsql
        ports:
            - "5432:5432"     
        volumes:
            - "./docker-web/data:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: pwd
            POSTGRES_DB: postgresql  
               